In [27]:
import numpy as np
import pandas as pd
import sklearn
import scipy
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report,accuracy_score
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor
from sklearn.svm import OneClassSVM
from pylab import rcParams
#from sklearn.cross_validation import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn import tree
from sklearn import preprocessing
data = pd.read_csv(r'C:\Users\hp\Code\python_practice\CDS_v1.csv',dtype={'label':object} )
print(data)

         _id                              name  \
0      10001                      01_say_hello   
1      10002        02_balance_address_checker   
2      10003                   03_basic_random   
3      10004               04_lottery_10_users   
4      10005  04_lottery_10_users_adamskrodzki   
...      ...                               ...   
62178  96207                             96207   
62179  96208                             96208   
62180  96209                             96209   
62181  96210                             96210   
62182  96211                             96211   

                                                    code               label  
0      pragma solidity ^0.4.22;\r\r\n\r\r\ncontract G...  000000000000000100  
1      pragma solidity ^0.4.22;\r\r\n\r\r\ncontract C...  000000000000000000  
2      pragma solidity ^0.4.23;\r\r\n\r\r\ncontract B...  000000000000000000  
3      pragma solidity ^0.4.23;\r\r\n\r\r\ncontract L...  000000000000000000  
4   

In [28]:
#multi cols of labels
#Create independent and Dependent Features
#data=split_label(data)
def split_label(data_frame):
    # Change 'label' to whatever naming used in the original DataFrame.
    temp_df = data_frame['label'].str.split("", n = -1, expand = True)
    for i in range(1, 19):
        data_frame[f'l{i}'] = temp_df[i]
    return data_frame

newdata=split_label(data)
le = preprocessing.LabelEncoder()
balance_data = newdata.apply(le.fit_transform)
#Y=balance_data
X = balance_data.values[:, :4]

Y = balance_data.values[:,4:]
# Print the shapes of X & Y
print(X)
print(X.shape)
print(Y)
print(Y.shape)


[[    0   326 40272     3]
 [    1   507 40246     0]
 [    2   711 42201     0]
 ...
 [62180 41152  9304   147]
 [62181 41153  5466   215]
 [62182 41154  5467   215]]
(62183, 4)
[[0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(62183, 18)


In [21]:
#multi class label binarizer
def split_label_binarizer(data_frame):
    # Change 'label' to whatever naming used in the original DataFrame.
    temp_df = data_frame['label'].str.split("", n = -1, expand = True)
    
    #import numpy as np
    #from sklearn import preprocessing
    lb = preprocessing.LabelBinarizer()
    template = ['0', '1']
    template = [int(i) for i in template]  
    lb.fit_transform(np.array([template]))
    # print(lb.classes_)
    
    cl = []
    for index in data_frame.index:
        temp = data_frame['label'][index]
        temp = [int(i) for i in temp] 
        # print(temp)
        # temp = temp[1:19]
        mat = lb.transform(temp)
        cl.append(mat)
    data_frame['lc'] = cl
    return data_frame
newdata=split_label_binarizer(data)
#print(newdata)

X = newdata.values[:, 0:4]

Y = newdata.values[:,4:]
# Print the shapes of X & Y
#print(X)
#print(X.shape)
print(Y)
print(Y.shape)

[[array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0]])]
 [array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])]
 [array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])]
 ...
 [array([[0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])]
 [array([[0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
     

In [24]:
#list
def split_label_binarizer(data_frame):
    # Change 'label' to whatever naming used in the original DataFrame.
    cl = []
    for index in data_frame.index:
        temp = data_frame['label'][index]
        temp = [int(i) for i in temp] 
        cl.append(temp)
    data_frame['lca'] = cl
    return data_frame
newdata=split_label_binarizer(data)
#print(newdata)

X = newdata.values[:, 0:4]

Y = newdata.values[:,4:]
# Print the shapes of X & Y
#print(X)
#print(X.shape)
print(Y)
print(Y.shape)

[[list([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0])]
 [list([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])]
 [list([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])]
 ...
 [list([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])]
 [list([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0])]
 [list([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0])]]
(62183, 1)


In [29]:
from imblearn.over_sampling import RandomOverSampler 
from imblearn.pipeline import make_pipeline
from imblearn.over_sampling import SMOTE
import random as r
# Implementing Oversampling for Handling Imbalanced 
#smk = SMOTE(random_state=42)
#fixed value is assigned like random_state = 0 or 1 or 42 or any other integer then no matter how many times you execute your code the result would be the same .i.e, same values in train and test datasets.
#smk=SMOTE(k_neighbors=2)
#X_res,y_res=smk.fit_sample(X,Y)
smk = SMOTE(random_state=42)
X_res,y_res=smk.fit_sample(X,Y)
print(X_res.shape,Y_res.shape)

ValueError: Imbalanced-learn currently supports binary, multiclass and binarized encoded multiclasss targets. Multilabel and multioutput targets are not supported.

In [ ]:
from collections import Counter
print('Original dataset shape {}'.format(Counter(Y)))
print('Resampled dataset shape {}'.format(Counter(y_over)))